# Generated by Django 2.2 on 2019-10-12 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_jobposting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='pic',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
