# Generated by Django 2.2 on 2019-10-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_testimonials_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='logo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
