# Generated by Django 2.2 on 2019-10-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191021_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='logo',
            field=models.FileField(upload_to='files/'),
        ),
    ]
