# Generated by Django 2.2 on 2019-10-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20191021_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('content', models.CharField(max_length=220)),
                ('link', models.CharField(max_length=220)),
            ],
        ),
    ]
