# Generated by Django 2.2 on 2019-10-29 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_newsandupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=440),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enroll',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enroll',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enroll',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=440),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
