# Generated by Django 2.2 on 2019-11-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_popupframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='country_code',
            field=models.CharField(default='+91', max_length=220),
        ),
        migrations.AddField(
            model_name='franchise',
            name='country_code',
            field=models.CharField(default='+91', max_length=220),
        ),
    ]
